version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    container_name: traefik
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--log.level=DEBUG"
      - "--log.filePath=/logs/traefik.log"
      - "--accessLog.filePath=/logs/access.log"
      - "--docker.domain=docker.localhost"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.strip-client-api-prefix.stripprefix.prefixes=/api"

#      look at client-api compose file to know why it's commented
#      - "traefik.http.middlewares.strip-docs.stripprefix.prefixes=/,/docs"
#      - "traefik.http.middlewares.docs-redirectregex.redirectregex.regex=^http://swagger.localhost/(.*).js"
#      - "traefik.http.middlewares.docs-redirectregex.redirectregex.replacement=http://swagger.localhost/docs/$${1}"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./logs:/logs # Add this line to mount a volume for logs
