################################################################
# Docker configuration backend
################################################################

# Docker configuration backend
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
    #defaultRule: "PathPrefix(`/.Name`)"

log:
  level: DEBUG
  filePath: /logs/traefik.log
  format: json

# API and dashboard configuration
api:
  insecure: true
